resourceCollections:
- name: service-bus
  type: microsoft.servicebus/namespaces
  criteria:
    subscriptions:
    - 0329dd2a-59dc-4493-aa54-cb01cb027dc2
- name: app-services-north-europe
  type: microsoft.web/sites
  criteria:
    regions:
    - northeurope
- name: app-services
  type: microsoft.web/sites
  criteria:
    regions:
    - northeurope
    - westeurope
- criteria:
    resourceGroups:
    - promitor-sources
  name: app-services-filtered
  type: microsoft.web/sites
- criteria:
    tags:
      app: promitor-sample
  name: logic-apps
  type: microsoft.logic/workflows